sync:
  defaults:
    mode: "one-way-safe"
    symlink:
      mode: "ignore"
    ignore:
      vcs: true
      paths:
        - .gitignore
        - ".php*.cache"
        - robots.txt
        - node_modules
        - sitespeed-result
        - web/app/uploads
        - wp-content/uploads
        - .well-known
        - vendor
        - .idea
        - ".env*"
        - .actrc
        - tmp
        - .cache
        - "*.po"
        - "*.sql"
        - wp-cli*.yml
        - web/app/languages
        - web/app/plugins
        - web/app/cache
        - web/app/nitropack
        - web/app/smush-webp
        - "!web/app/plugins/wp-object-cache"
        - debug.log
        - .DS_Store
        - yarn-error.log
        - .eslintcache
        - web/**/*.xml
        - mutagen.yml*
        - "*/nitropack/*"
    permissions:
      defaultFileMode: 644
      defaultDirectoryMode: 755
